[package]
name = "testfileFTP"
version = "0.1.0"
edition = "2021"

[dependencies]
libunftp = "0.20.1"
unftp-sbe-fs = "0.2.5"
tokio = { version = "1", features = ["full"] }
config = "0.14.0"
serde = "1.0.203"
dotenvy = "0.15.7"
anyhow = "1.0.86"
